USE `sismos`;

INSERT INTO zona (nombre) 
VALUES ('Norte'),
('Sur'),
('Centro'),
('Oriente'),
('Poniente');

INSERT INTO estados (nombre_estado) VALUES
('Aguascalientes'),
('Baja California'),
('Baja California Sur'),
('Campeche'),
('Chiapas'),
('Chihuahua'),
('Ciudad de México'),
('Coahuila'),
('Colima'),
('Durango'),
('Guanajuato'),
('Guerrero'),
('Hidalgo'),
('Jalisco'),
('México'),
('Michoacán'),
('Morelos'),
('Nayarit'),
('Nuevo León'),
('Oaxaca'),
('Puebla'),
('Querétaro'),
('Quintana Roo'),
('San Luis Potosí'),
('Sinaloa'),
('Sonora'),
('Tabasco'),
('Tamaulipas'),
('Tlaxcala'),
('Veracruz'),
('Yucatán'),
('Zacatecas');

INSERT INTO deleg_mun(nombre_delegacion,Estados_idEstados) VALUES
('Álvaro Obregón',7),
('Azcapotzalco',7),
('Benito Juárez',7),
('Coyoacán',7),
('Cuajimalpa de Morelos',7),
('Cuauhtémoc',7),
('Gustavo A. Madero',7),
('Iztacalco',7),
('Iztapalapa',7),
('Magdalena Contreras',7),
('Miguel Hidalgo',7),
('Milpa Alta',7),
('Tláhuac',7),
('Tlalpan',7),
('Venustiano Carranza',7),
('Xochimilco',7);